Myblog/urls.py
# Importa las funciones y configuraciones necesarias de Django para administrar la aplicación.
from django.contrib import admin
from django.urls import path, include


# Importa la función 'static' para manejar archivos estáticos y multimedia
from django.conf.urls.static import static

# Importa la configuración global del proyecto Django desde settings.py.
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Lista de patrones de URL para el enrutamiento de la aplicación.
urlpatterns = [
    # Ruta para acceder al panel de administración de Django.
    path('admin/', admin.site.urls),
    
    # Ruta principal que incluye las URL definidas en el archivo main.urls.
    path('', include('main.urls'))
]

urlpatterns += staticfiles_urlpatterns()
# # Configuración para servir archivos estáticos y multimedia durante el desarrollo
# if settings.DEBUG:
#     # Agrega las URL para servir archivos multimedia (MEDIA_URL) usando la ruta del sistema de archivos especificada en MEDIA_ROOT
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='Main'

urlpatterns = [
    path('', views.home, name='Home'),
    # URL DE BLOG, RECIBE COMO PARAMETRO EL ID DEL POST QUE DESEAMOS VER
    path('blog/<int:blog_id>/', views.blog, name='Blog')

]

main/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    #La línea unique=True se aplica al campo title. Esto significa que cada valor en el campo title debe ser único en toda la tabla de la base de datos. No puede haber dos filas con el mismo valor en el campo title.
    titulo = models.CharField(max_length=200, blank=True, null=True, unique=True) 
    
    # #Auto-generación: El campo slug se utiliza para almacenar una versión "amigable" del título que puede ser utilizada en la URL. Este campo se auto-genera a partir del título, y su propósito es crear una URL legible y SEO-friendly.
    # slug = models.SlugField(max_length=200, unique=True)
    
    # Este campo se utilizará para almacenar textos más largos, sin una longitud máxima predefinida.
    description = models.TextField(blank=True, null=True)

    texto= models.TextField(blank=True, null=True)
    
    imagen= models.ImageField(upload_to="blog", blank=True, null=True)
    # Este campo se utilizará para almacenar fechas y horas. 'auto_now_add=True' establece la fecha automáticamente al agregar un nuevo registro.
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
        
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    
    #rdering = ['-created_on'] significa que, por defecto, los objetos de la clase Post se ordenarán en orden descendente según el campo created_on. Esto implica que los posts más recientes se mostrarán primero cuando realices consultas a la base de datos sin especificar un orden diferente.
    class Meta:
        ordering = ['-created'] 
        
    def __str__(self):
        return self.titulo
    
    

main/views.py
from django.shortcuts import render, redirect

from .models import Post
# Create your views here.

def home(request):
    datos = Post.objects.all()
    
    context = {
        'datos': datos
    }
    
    return render(request, 'cards.html', context)


def blog(request, blog_id):
    # Con el id usando el metodo  get(. recordando que el metodo get() en un modelo de Django se utiliza para recuperar un único objeto que cumple con los criterios de búsqueda especificados. 
    dato=Post.objects.get(id=blog_id)
       
    
    context = {
        'dato_post': dato
    }
    
    # renderizamos el item especifico obtenido a nuestra plantilla
    return render(request, 'post.html', context)

main/templates/base.html
<!-- Cargamos las etiquetas estáticas para acceder a archivos estáticos como CSS y JavaScript -->
{% load static %}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do-App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

   

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Enlace a Google Fonts para tipos de fuentes -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Playpen+Sans:wght@200;300&display=swap"
        rel="stylesheet">

    <!-- Cargar estilos CSS personalizados desde archivos estáticos -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    
    <title>Blog</title>
</head>

<body class="fondo">
   
    {% comment %} inclusion de la barra de navegacion (navbar) desde la carpeta /templates/includes {% endcomment %}
    {% include 'includes/navbar.html' %}


    

    <!-- comienza contenido -->
    {% block content %}

    {% endblock %}
    <!-- termina contenid contenido -->








    <!-- comienza footer -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>


</html>

main/templates/cards.html
<!-- Extiende la plantilla "base.html" -->
{% extends "base.html" %}

<!-- Cargamos las etiquetas estáticas para acceder a archivos estáticos como CSS y JavaScript -->
{% load static %}

{% comment %} inicia contenido {% endcomment %}
{% block content %}

    {% comment %} inclusion de l encabezado (header)  desde la carpeta /templates/includes {% endcomment %}
    {% include 'includes/titulo.html' %}


    {% comment %} Este es un bucle for que itera sobre 'datos'   {% endcomment %}
    {% for i in datos %} 
    <!-- forloop.counter0 es el índice actual del ciclo (comenzando desde 0), Esto puede ser útil, por ejemplo, si estás generando una cuadrícula de elementos y quieres que cada fila tenga exactamente 3 elementos. -->
        {% if forloop.counter0|divisibleby:3 %}
        <!-- divisibleby es un filtro de plantilla que devuelve True si el valor es divisible por el argumento. Por lo tanto, {% if forloop.counter0|divisibleby:3 %} verifica si el índice actual es divisible por 3, y si es así, agrega un nuevo contenedor. -->


        <!-- publicaciones -->
        <!-- Aquí, justify-content-center se utiliza para centrar horizontalmente las columnas dentro de la fila. -->
            <div class="row d-flex  px-5 mx-5 d-flex justify-content-center">
            {% endif %}
            {% endif %}
                <!-- fila 1 -->
                <!-- Aquí, justify-content-center se utiliza junto con d-flex para centrar el contenido de la tarjeta dentro de la columna. Esto significa que la tarjeta se centrará horizontalmente dentro de la columna12. -->
                <div class="col-lg-3 col-sm-12 mb-2 mb-lg-5 mt-3 mt-lg-5 d-flex justify-content-center ">
                    <div class="card text-center" style="width: 18rem;">
                        <img src="{{ i.imagen.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ i.titulo }}</h5>
                            <p class="card-text">{{ i.description }}</p>
                            {% comment %} EETIQUETA DE ANCLAJE QUE CREARÁ UN ENLACE A 'MAIN:BLOG' ENVIANDO COMO PARAMETRO 'I.ID' , MAIN ES EL NOMBRE DE APP_NAME EN EL ARCHIVO URLS, Y BLOG EL NOMBRE DE LA URL, EL ID LO OBTENEMOS DEL CICLO FOR   {% endcomment %}
                            <a href="{% url 'Main:Blog' i.id %}" class="btn btn-primary">View Blog Details</a>
                        </div>
                    </div>
                </div>
            
            {% comment %} lo que hace este código es cerrar un bloque <div> cada vez que forloop.counter es divisible por 3, o si es la última iteración del bucle {% endcomment %}
        {% if forloop.counter|divisibleby:3 or forloop.last %}    
                </div>
        {% endif %}
    {% endfor %}
    {% comment %} termina contenido {% endcomment %}

{% endblock %}

{% comment %} 
 `forloop.counter0` y `divisibleby` son características de las plantillas de Django
    

1. **forloop.counter0**: En las plantillas de Django, cuando estás dentro de un bucle `{% for %}`, puedes usar `forloop.counter0` para obtener el índice actual del bucle, comenzando desde 0¹³. Por ejemplo, si estás iterando sobre una lista de 5 elementos, `forloop.counter0` será 0 en la primera iteración, 1 en la segunda, y así sucesivamente hasta 4 en la última iteración¹³.

2. **divisibleby**: `divisibleby` es un filtro de plantilla de Django que devuelve `True` si el valor es divisible por el argumento, y `False` en caso contrario⁶⁷. Por ejemplo, si tienes un número y quieres verificar si es divisible por 3, podrías usar `{% if value|divisibleby:3 %}` en tu plantilla⁶⁷.

3.forloop.last: Es otra variable que Django proporciona automáticamente dentro de un bucle for, que es True si la iteración actual es la última del bucle, y False en caso contrario. {% endcomment %}

main/templates/includes/navbar.html
{% load static %}
    <!--inicio barra de navegacion-->
    <header>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary fixed-top ">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Toggle button -->
                <button data-mdb-collapse-init class="navbar-toggler" type="button"
                    data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->

                    <!-- icono de barrra de nav -->
                    <a class="text-reset me-3" href="#">
                        <i class="fas fa-blog"></i>

                    </a>

                    <!-- icono de barrra de nav -->



                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Main:Home' %}">Home</a>
                        </li>

                    </ul>
                    <!-- Left links -->
                </div>
                <!-- Collapsible wrapper -->

                <!-- Right elements -->
                <div class="d-flex align-items-center">



                    <!-- Avatar -->
                    <div class="dropdown">
                        <a data-mdb-dropdown-init class="dropdown-toggle d-flex align-items-center hidden-arrow"
                            href="#" id="navbarDropdownMenuAvatar" role="button" aria-expanded="false">
                            <img src="{% static 'img/japon.jpg' %}" class="" height="25"
                                alt="Japan flag" loading="lazy" />
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
                            <li>
                                <a class="dropdown-item" href="#">My profile</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Settings</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Right elements -->
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

    </header>
    <!--fin barra de navegacion-->

main/templates/includes/titulo.html
{% load static %}

    <!-- La clase 'container' establece un ancho máximo en todos los dispositivos y permite un relleno automático. Las clases 'd-flex' y 'justify-content-center' se utilizan para centrar el contenido horizontalmente. 'mt-1' añade un margen superior de 0.25rem (1 rem es igual al tamaño de fuente actual). -->
    <div class="container d-flex justify-content-center mt-1">
        <!-- La clase 'text-center' centra el texto y 'text-white' cambia el color del texto a blanco. 'mt-5' añade un margen superior de 3rem. -->
        <div class="text-center text-white mt-5">
            <!-- Título de bienvenida. La clase 'mt-5' añade un margen superior de 3rem y 'tipoLetra'  clase personalizada que define la fuente y  'style="font-size: 4em;"' aumenta el tamaño de la fuente a 4 veces el tamaño de fuente actual. -->
            <h1 class="mt-5 tipoLetra" style="font-size: 4em;">Welcome</h1>
            <!-- Título de las publicaciones del blog. La clase 'mt-0' elimina el margen superior y 'tipoLetra' clase personalizada que define la fuente  'style="font-size: 3em;"' aumenta el tamaño de la fuente a 3 veces el tamaño de fuente actual. -->
            <h1 class="mt-0 tipoLetra" style="font-size: 3em;">Blog Posts</h1>
        </div>
        <!-- Fin del contenedor principal -->
    </div>

main/templates/post.html
<!-- Extiende la plantilla "base.html" -->
{% extends "base.html" %}

<!-- Cargamos las etiquetas estáticas para acceder a archivos estáticos como CSS y JavaScript -->
{% load static %}

<!-- Inicia contenido -->
{% block content %}
    <!-- Inicio de la sección -->
    {% comment %} nuestra @plantilla recibe la informacion enviada en el contexto por nuestra viista def blog(re..), y usando nomenclatura de clases accedemos a los datos de ese item en especifico {% endcomment %}
    <section>
        <!-- La clase 'container' establece un ancho máximo en todos los dispositivos y permite un relleno automático. Las clases 'd-flex', 'justify-content-center' y 'align-items-center' se utilizan para centrar el contenido horizontal .  'mt-1' añade un margen superior de 0.25rem (1 rem es igual al tamaño de fuente actual). -->
        <div class="container d-flex justify-content-center  ">
            <!-- La clase 'text-center' centra el texto y 'text-white' cambia el color del texto a blanco. 'mt-5' añade un margen superior de 3rem. -->
            <div class="text-center text-white mt-5 pt-5">
                <!-- Título del blog. La clase 'mt-5' añade un margen superior de 3rem y 'tipoLetra' es una clase personalizada que define la fuente. 'style="font-size: 4em;"' aumenta el tamaño de la fuente a 4 veces el tamaño de fuente actual. -->
                <h1 class="mt-5 tipoLetra" style="font-size: 4em;">{{ dato_post.titulo }} </h1>
            </div>
        </div>
        <!-- Fin de la sección -->
    </section>
    
    <section class="container my-3" >
    <div class="d-flex " >
        
        <div class=" px-4 " style="clear: both;">
            <img src="{{ dato_post.imagen.url }}" class="img-fluid float-start pe-5 mt-4" width=50% alt="Imagen del Blog">
        
            <p class="mt-3 mb-3 ml-3 mr-3 lh-lg text-white fs-5 fst-italic" style="text-align:justify">{{ dato_post.texto }}</p>
        </div>
      </div>
    
    </section>

{% endblock %}